### ISSUE TITLE
Make latest release carry git hash in version.

### ISSUE THREAD

**Issue by jonasthewolf** [jonasthewolf/gsn2x#157]
https://stackoverflow.com/questions/52176130/how-to-tell-cargo-to-use-git-tags-to-determine-the-crate-version

**Comment by kinnison** [comment]
If you are interested, I could knock up a PR to add this with git-testament which is the implementation we use in rustup

**Comment by jonasthewolf** [comment]
Thank you very much for your offer, @kinnison 
Your support is very much appreciated.
After our short chat I had a chance today digging deeper into rustup's solution.
I can understand the use case, however, I would like to keep the number of dependencies as low as possible, and, thus, follow the above linked workflow.
Thanks.

**Comment by kinnison** [comment]
Fair enough. I appreciate the desire to keep a small dependency set. Good luck
