### ISSUE TITLE
Rendering of references

### ISSUE THREAD

**Issue by jsavage** [jonasthewolf/gsn2x#166]
Hi, just a quick note to mention that the GSN node references are not being rendered clearly.
The example below was obtained using latest windows release and latest examples document.
![image](https://user-images.githubusercontent.com/189524/193860046-1eaa126e-2bd9-473a-b280-49789c34a3ea.png)

**Comment by jonasthewolf** [comment]
Hi James, thanks for the feedback. I am also not satisfied with the current rendering. However, my past tries to improve the rendering did not yield success. I will have another look into it.

**Comment by jonasthewolf** [comment]
Hi @jsavage,
I just released v2.4.3.
Could you please check if the IDs are more readable now?
Thanks
Best regards,

Jonas

**Comment by jsavage** [comment]
Hi @jonasthewolf, this issue is resolved perfectly.  Thank you.  Checked using  [examples/example.gsn.yaml](https://github.com/jonasthewolf/gsn2x/blob/master/examples/example.gsn.yaml) but also my own work.
![image](https://user-images.githubusercontent.com/189524/194898865-8027758b-a32f-406b-bf84-1f10d4fdafdb.png)
