### ISSUE TITLE
Validation of YAML

### ISSUE THREAD

**Issue by jsavage** [jonasthewolf/gsn2x#176]
Hi @jonasthewolf 
Maybe its just my inexperience working with JSON but as my GSN network grows so does the challenge of validation.
My experience of using other tools for this is mixed.   I am using visual studio code out of the box for editing and have been trying the YAML validator from [jsonformatter.org](https://jsonformatter.org/yaml-validator).  However, this recently proved inadequate against a very noddy typo as shown at the bottom of the page.  Other validators such as http://www.yamllint.com/ also failed to detect this so perhaps I am expecting too much from those tools.

I do think others who try gsn2x would value some advice on this topic - even if that is just a few links to freely available tools or some suggested validation rules that can be added to the likes of VSC or Notepad++ or another widely used editor.
 
The other thought I had when debugging this was whether the accuracy of the line number reported in  this type of error message could be improved - especially when it relates to invalid YAML like that causing this error.
![image](https://user-images.githubusercontent.com/189524/195331337-b8f0450e-ad7f-4e11-b4e6-8857a9c5522a.png)

Although I can now see the cause, as you can see, the YAML was still showing as valid. 
![image](https://user-images.githubusercontent.com/189524/195328855-dd006c74-f637-4301-98b2-7b3a9ca09fb6.png)

**Comment by jonasthewolf** [comment]
Hi @jsavage, again this is the same issue as #74.
The root cause in rust/serde was closed and recently re-opened here: https://github.com/serde-rs/serde/issues/2157
Let's hope that we get that fixed.
