### ISSUE TITLE
Option -o output dir does not change directories for module relevant outputs

### ISSUE THREAD

**Issue by Ilidur** [jonasthewolf/gsn2x#277]
**Describe the bug**
Module related files do not respect the -o flag. After further testing it seems like it uses the folder of the files inputted, which would be wrong behaviour as the binary was called in a folder one level up.

**To Reproduce**
This is a minimal YAML that reproduces the example:
The example given in: https://jonasthewolf.github.io/gsn2x/modular_extension.html#developing-undeveloped-elements-from-other-modules
command run `.bin/gsn2x -o gsn-output src/*.gsn` 

where:
*.gsn are gsn yaml files stored in ./src/
./gsn-output/ is the cached outputs for svg
and ./bin/ is where the binary is stored.

This results in the `architecture.svg`, `complete.svg` and `evidences.md` stored in `./src/` not in `./gsn-output/`

**Expected behavior**
The option -o should set the output folder such that the base folder can be kept clean, all output files kept in one place, and the folder can be excluded from git.
Alternatively another flag can be provided to set the output folder of the module related files.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version [e.g. 11]
 - Browser [e.g. chrome, safari] that is used for viewing the SVG: SVG preview VSCode

**Additional context**

**Comment by jonasthewolf** [comment]
@Ilidur thanks for the feedback.
What do you mean by module specific files?
I just created #276 this morning, because e.g. architecture view is not output correctly.
If the individual modules files are not output correctly, please let me know the version of gsn2x you are using.

**Comment by jonasthewolf** [comment]
I marked #276 as duplicate.
Thanks for the precise description @Ilidur .
I will try to address that issue as soon as possible.

**Comment by jonasthewolf** [comment]
I just released [v2.8.0](https://github.com/jonasthewolf/gsn2x/releases/tag/v2.8.0) that includes the fix.
