### ISSUE TITLE
Layer option does not render well.

### ISSUE THREAD

**Issue by Rlaks10** [jonasthewolf/gsn2x#358]
If additional layers are added it is displayed further away from the element. 

used command: 
> gsn2x.exe -w 30  "AssuranceCase.yaml" -l status

![AssuranceCase](https://github.com/jonasthewolf/gsn2x/assets/156221075/dc2d1550-4851-4143-9cac-51d1411a5293)

**Comment by jonasthewolf** [comment]
@Rlaks10 thanks for the feedback.
I consider this a bug.
Let me try to fix that over the weekend.

**Comment by Rlaks10** [comment]
Hmm another one may be related. Here i extended the same example with classes (with embedded css) and using modules. The text in submodules are not rendered for all the goals (supportedBy: ), in which are added in its own module but without its classes. 

used command:
> gsn2x.exe -w 30 "AssuranceCase.yaml" "G1.yaml" "G2.yaml" "G3.yaml" "G4.yaml" "G5.yaml" "G6.yaml" "G7.yaml" -s gsn2x.css -t -l status 


![image](https://github.com/jonasthewolf/gsn2x/assets/156221075/606b18e7-cc93-4fa0-bd83-4fa17dafa795)

**Comment by jonasthewolf** [comment]
Actually, I assume it is exactly the same bug. The text of additional layers should be taken into account when rendered...

**Comment by jonasthewolf** [comment]
@Rlaks10 I just released v3.0.2.
That should fix the issue you discovered.
Thanks again for the feedback.

**Comment by Rlaks10** [comment]
I just checked it. now the layer thing is working fine. But the text is still rendered in white.  I did some testing and figured out that if I am including option "url", then the text is rendered white. If the URL is removed than it is fine. 

eg:
> 'G0-TopLevelGoal:
  text: It is OK to use to develop _this_ functionality/application(because)
  inContextOf: [A1]
  supportedBy: [S1]
  status: draft
  classes: [status-yellow]

A1:
  text: _This_ function/application itself is *safe and secure*
  status: draft
  url: https://example.com
   
S1:
  text: Argue over all engineering steps* where data* is manipulated/created/.
  supportedBy: [G1, G2, G3, G4, G5, G6, G7]
  inContextOf: [C1, C2]
  status: draft

C1:
  text: All relevant data* is known
  status: draft
      
C2: 
  text: All relevant steps* are identified
  url: https://example.com
  status: draft'

![image](https://github.com/jonasthewolf/gsn2x/assets/156221075/edc6992c-f27f-47af-9704-5b3b2507cc8f)

**Comment by jonasthewolf** [comment]
@Rlaks10  would you mind sharing the relevant CSS part?
You would have expected the url being rendered in black by default, right?

**Comment by Rlaks10** [comment]
sure. here is the content of css file. 

> .status-normal path { fill: white; }
.status-normal text,a { fill: black; }
.status-green path { fill: green; }
.status-green text,a { fill: black; }
.status-yellow path { fill: orange; }
.status-yellow text,a { fill: black; }
.status-red path { fill: red; }
.status-red text,a { fill: white; }
g:hover {stroke:  black;}

**Comment by Rlaks10** [comment]
Is it possible to add the color encoding the architecture diagram as well? Architecture diagram picks up the module descriptions, but text again is not rendered.I am using hover function to see the contents now. 

![image](https://github.com/jonasthewolf/gsn2x/assets/156221075/91bda8e0-3299-4034-a781-2b7100cf4c7d)

**Comment by jonasthewolf** [comment]
@Rlaks10  please see #367
