### ISSUE TITLE
Circular reference not identified

### ISSUE THREAD

**Issue by DoctorGM** [jonasthewolf/gsn2x#41]
Hello,
thanks for writing this tool. It looks really useful. Whilst playing I noticed that a circular reference was not found. Here's the example input I used.

G1:
  text: This is a Goal
  supportedBy: [S1]

S1:
  text: This is a Strategy.
  supportedBy: [G2.1]
  
G2.1:
    text: subgoal
    # circular reference!!
    supportedBy: [G1]

Very best regards...
gary

**Comment by jonasthewolf** [comment]
Hi Gary,
thanks for the feedback.
You are right.
I never thought of circular references, because they would be immediately identified in the graphical views.
Let me take this as a feature.
Best regards, 
Jonas

**Comment by DoctorGM** [comment]
Hi Jonas,
many thanks for your rapid responses. Yes - I agree... you can detect these things from the graphical view. However, there are also other problems that can be detected from the graphical view that you do check for. Also, the ability to check for "consistency" (i.e. syntactical correctness, no cycles, all goals etc. with solutions, ...) is very useful. Engineer's time is expensive and scriptable automated checks allows engineers not to worry about those checks (not all, though, obviously :-).

Many thanks...
gary

**Comment by jonasthewolf** [comment]
Hi Gary,
Thanks for the feedback. I agree that is definitely sensible feature. I see what I can do 😉
Do you by chance have some experience if multiple "root" nodes are actually sensible in GSN?
In the one file solution, I enforced that by an error during validation.
However, I was wondering if this is actually a good idea.

Best regards,

Jonas

**Comment by DoctorGM** [comment]
Hi Jonas,
I'm sorry to make this your problem :-( If I new Rust I'd help you out. I've been looking for a project to build so that I can learn a new language for some time and wondered about a DSL for GSN, either in Python or Rust or something. Then a colleague spotted gsn2x. So now I'll have to think of something else :-)

As for multiple top-level goals... <sigh>... I think that one of the problems with GSN is that Tim (as far as a I can tell) did not define a formal grammar and semantics for it (although, I must admit, I have not popped into the library and read his thesis). So questions like this will arise.

I tried to work out some syntax/semantics from the GSN Community Standard V3. However, it's not possible to get many hints from that document. Certainly a single top-level goal is implied rather than stated (in my reading of it, anyway).

As for **my** experience of multiple top-level goals I have to confess that I am a relative newcomer to GSN and am currently evaluating GSN along with tool support for some of our safety-relevant projects.

My feeling is that there may well be multiple safety goals in a project. For example, let's say that there is a product that consists of two other products - so there are three things for sale: A, B and C (which is the union of A & B).

I would want a safety argument for A, one for B and one for C.

So A and B have, at least, one top-level goal each.

Can I then create the safety argument for C by another top-level goal that references A's argument, B's argument along with some "the composition of the two is safe" argument? I would hope so :-)

So we'd have 3 top-level goals. The graphs for A & B should verify correctly without C, and C should verify without needing modifications to A & B (hopefully).

I think that your method for supporting external modules (if I understand it correctly) would work well for this structure, although the graph might get rather large :-)

Another interpretation of your question might be "if there are a use case for multiple top-level goals in the same GSN diagram"? If the two graphs are disjoint then I would say "no". Just have two files.

However, if the two graphs are not disjoint then I can see what you might want to put them in the same file in order to share sub-goals, etc. I would try not to do this (although I have no relevant experience upon which to base this gut feeling). I would try to partition the graphs across multiple files in order to make the verification process a bit easier.

I'm not sure if this reply helps. But I'm happy to consider this further if you wish.

Very best regards...
gary

**Comment by DoctorGM** [comment]
Hi Jonas,
I'm sorry that I incorrectly closed this Issue. I'm new to github :-(

Very best regards...
gary

**Comment by jonasthewolf** [comment]
This is resolved with v2.0.0.
