### ISSUE TITLE
undeveloped goal displayed as box containing "2662"

### ISSUE THREAD

**Issue by DoctorGM** [jonasthewolf/gsn2x#42]
Hello,
Using Adobe Acrobat Reader DC under Windows, the diamond that should be displayed under an undeveloped goal is instead displayed as a box containing "2662".  Here's my input source:

G1:
  text: This is a Goal
  undeveloped: true

I've uploaded a file with a screenshot.

![2022-02-21_13h35_45](https://user-images.githubusercontent.com/100131010/154965607-7543dd38-7752-426b-8fd7-2aa7e8624b6f.jpg)

As I'm sure you know, 2662 is hex for the white diamond character. So I guess that something is not quite right with Acrobat reader. So I'm not sure where the problem is here: is Acrobat Reader broken or are you producing output code that Dot incorrectly renders.

So not to be more helpful.

Many thanks...
gary

**Comment by jonasthewolf** [comment]
I think this is not an issue with Acrobat, but the font that used by dot to create the PDF.
There are multiple options to change it, after the dot file has been generated.
I suggest looking at the SVG in the first place.
SVGs can be viewed in all modern browsers.

**Comment by jonasthewolf** [comment]
Hi @DoctorGM, I just released a major rework including writing my own backend instead of relying on graphviz.
Feedback is very much appreciated.
With that release I also solved that issue here.
Done with v2.0.0
