### ISSUE TITLE
Spelling mistake in command line options?

### ISSUE THREAD

**Issue by DoctorGM** [jonasthewolf/gsn2x#43]
Hello,
I was looking through main.rs and spotted this...

            Arg::with_name("EVIDENCES")
                .help("Additionally output list of all evidences in given file.")
                .short("e")
                .long("evicdenes") <<<<<<<<<<<<< spelling mistake?
                .takes_value(true)
Regards...
gary

**Comment by jonasthewolf** [comment]
Thanks, I already noticed that one too and fixed it locally. It will be part of the next release.
