### ISSUE TITLE
-o, -a, -f -m options are documented but appear unsupported

### ISSUE THREAD

**Issue by DoctorGM** [jonasthewolf/gsn2x#44]
Hello again,
I'm not a Rust programmer. So this could be a load of nonsense. So I apologise now.

I'm trying to get the module extensions working and having no success. The -f, -a and -m options just give error messages.

From looking in main.rs. The command line parser seems to be set up for:
- only one input file
- none of the options -f, -a and -m options.

Also, gsn2x --help does not report these options.

This disagrees with the documentation.

Many thanks...
gary

**Comment by jonasthewolf** [comment]
Hi Gary,

that is because I was not that clean on using branches 😉
Support for module extension is still in the making.
I updated already the documentation in master, but still working on the implementation.

Best regards,

Jonas

**Comment by DoctorGM** [comment]
Hi Jonas,
            Many thanks for replying to promptly. And sorry to give such a flurry of problems.

I would be very interested to know when module support works.

Very best regards…
gary

Mit freundlichen Grüßen / Best regards

Gary Morgan

Cross Functional Epic Owner
Safety Processes (ETAS-VOS/XEO2)
Robert Bosch GmbH | Postfach 10 60 50 | 70049 Stuttgart | GERMANY | www.bosch.com
Tel. +44 1904 562584 | Mobile +44 797 3115762 | ***@***.******@***.***>

Registered Office: Stuttgart, Registration Court: Amtsgericht Stuttgart, HRB 14000;
Chairman of the Supervisory Board: Prof. Dr. Stefan Asenkerschbaumer; Managing Directors: Dr. Stefan Hartung,
Dr. Christian Fischer, Filiz Albrecht, Dr. Markus Forschner, Dr. Markus Heyn, Rolf Najork
​

**Comment by jonasthewolf** [comment]
Hi Gary,
I can let you know when I have released the new version with module support.
If you add me as a contact (https://www.linkedin.com/in/jonas-wolf-7997b952/), I'll drop you a message.
Best regards,
Jonas

**Comment by DoctorGM** [comment]
Hi Jonas,
I'm afraid that I rarely use linkedin. But I think that I might have sent you some details. Forgive my lack of experience with it,

Very best regards...
gary
