### ISSUE TITLE
Cycles not detected

### ISSUE THREAD

**Issue by DoctorGM** [jonasthewolf/gsn2x#47]
Hi Jonas,
many thanks for the new version. I've had a quick play.

Issue 41 is marked as fixed/closed. I can't re-open it, but it appears not to be fixed. Here's my simple example...

G1:
  text: This is a Goal
  supportedBy: [S1]

S1:
  text: This is a Strategy.
  supportedBy: [G2.1]
  
G2.1:
    text: subgoal
    # circular reference!!
    supportedBy: [G1]

This contains a cycle but no error message is generated by gsn2x.

Many thanks...
gary

**Comment by jonasthewolf** [comment]
Thanks, @DoctorGM. That is interesting, since I have exactly that test case implemented.
I will check that today.

**Comment by jonasthewolf** [comment]
Hi @DoctorGM, I found the root cause.
The program expects that there is at least one unreferenced element.
Your example does not have that. I extended the check for unreferenced elements and the documentation in the #49 MR.
I will release it later today.
Thanks again.
