### ISSUE TITLE
gsn2x panics

### ISSUE THREAD

**Issue by DoctorGM** [jonasthewolf/gsn2x#48]
Hi Jonas,
this example input file

G1:
  text: This is a Goal
  undeveloped: true

with the command line...
gsn2x bug2.yaml

causes...

: c:\bin\gsn2x bug2.yaml
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\dirgraphsvg\graph.rs:78:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Let me know if you need a backtrace.

Many thanks...
gary

**Comment by jonasthewolf** [comment]
@DoctorGM I just released v2.1.0 that should fix the problems you found. Thanks again for the feedback.
