### ISSUE TITLE
Enhancement request - Support for comments

### ISSUE THREAD

**Issue by jsavage** [jonasthewolf/gsn2x#78]
Maybe I have overlooked a way to do this but I feel that the ability to add comments to the YAML would be helpful.
Not only single line comments but support to enable whole sections of the content to temporarily disabled - eg during debugging or to enable sections of a large GSN to be rendered separately from other sections.

**Comment by jonasthewolf** [comment]
Hi @jsavage,
That is possible by the YAML standard already.

```
# G-Commented:
#   text: Text

G-Uncommented:
  text: another text

```
